name: Update README.md

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 12 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - run: |
         git clone https://github.com/kevnnard/kevnnard.git
         git remote add main https://github.com/kevnnard/kevnnard.git
         cd kevnnard
         ls -a

      - run: |
         git config --global user.name bot-kevnanrd
         git config --global user.email londonokevin9@gmail.com

      - run: echo Hello >> README.md
      
      - run: |
         git status
         git branch
         git log

      - run: |
         git add .
         git diff --quiet && git diff --staged --quiet || git commit -m "[bot] Update README with latest info"
         git push origin main
