name: Update README.md

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 12 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - run: |
         git clone https://github.com/kevnnard/kevnnard.git
         cd kevnnard

         git config user.name "bot-kevnanrd"
         git config user.email londonokevin9@gmail.com

         git remote set-url origin https://github.com/kevnnard/kevnnard.git
        
         echo Hello >> README.md
         
         git add README.md
         git diff --quiet && git diff --staged --quiet || git commit -m "[bot] Update README with latest info"

         git push
