name: Update README.md

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 1 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
    steps:
     - name: Checkout repository
       uses: actions/checkout@v2
          
     - run: git clone https://github.com/kevnnard/kevnnard.git
      
     - run: |
         cd kevnnard
         
         git config --global user.name "bot-kevnanrd"
         git config --global user.email "londonokevin9@gmail.com"

         git remote set-url origin git@github.com:kevnnard/kevnnard.git

     - run: |
         cd kevnnard

         git branch patch-1
         
         echo Hello >> README.md
         git add README.md
         git diff --quiet && git diff --staged --quiet || git commit -m "[bot] Update README with latest info"
         
     - run: |
         cd kevnnard
         
         git push
